-- Auto-generated by colors.sh - DO NOT EDIT MANUALLY
-- Unified semantic tokens for neovim

return {
  -- Base colors
  bg = "#282828",
  bg_dark = "#1d2021",
  fg = "#ebdbb2",
  
  -- Semantic tokens
  primary = "#fabd2f",
  secondary = "#83a598",
  border = "#fabd2f",
  border_inactive = "#7c6f64",
  
  -- Syntax colors (from theme - Gruvbox Modern)
  red = "#cc241d",
  red_bright = "#fb4934",
  green = "#98971a",
  green_bright = "#b8bb26",
  yellow = "#d79921",
  yellow_bright = "#fabd2f",
  blue = "#458588",
  blue_bright = "#83a598",
  purple = "#b16286",
  purple_bright = "#d3869b",
  aqua = "#689d6a",
  aqua_bright = "#8ec07c",
  orange = "#d65d0e",
  orange_bright = "#fe8019",
  gray = "#7c6f64",
}
