-- Auto-generated by colors.sh - DO NOT EDIT MANUALLY
-- Unified semantic tokens for neovim

return {
  -- Base colors
  bg = "#16181a",
  bg_dark = "#0a0a0a",
  fg = "#ffffff",
  
  -- Semantic tokens
  primary = "#bd5eff",
  secondary = "#5ef1ff",
  border = "#bd5eff",
  border_inactive = "#7b8496",
  
  -- Syntax colors (from theme - Gruvbox Modern)
  red = "#ff6e5e",
  red_bright = "#ff8e7e",
  green = "#5eff6c",
  green_bright = "#7eff8c",
  yellow = "#f1ff5e",
  yellow_bright = "#ffff7e",
  blue = "#5ea1ff",
  blue_bright = "#7eb1ff",
  purple = "#bd5eff",
  purple_bright = "#dd7eff",
  aqua = "#5ef1ff",
  aqua_bright = "#7ef1ff",
  orange = "#ffbd5e",
  orange_bright = "#ffdd7e",
  gray = "#7b8496",
}
