-- Auto-generated by colors.sh - DO NOT EDIT MANUALLY
-- Unified semantic tokens for neovim

return {
  -- Base colors
  bg = "#16181a",
  bg_dark = "#0a0a0a",
  fg = "#ffffff",
  
  -- Semantic tokens
  primary = "#6857e4",
  secondary = "#ff9ced",
  border = "#6857e4",
  border_inactive = "#7b8496",
  
  -- Syntax colors (from theme - Gruvbox Modern)
  red = "#ff9ced",
  red_bright = "#ff8e7e",
  green = "#87ffbd",
  green_bright = "#7eff8c",
  yellow = "#ffe187",
  yellow_bright = "#ffff7e",
  blue = "#5ea1ff",
  blue_bright = "#7eb1ff",
  purple = "#6857e4",
  purple_bright = "#dd7eff",
  aqua = "#82fff6",
  aqua_bright = "#7ef1ff",
  orange = "#ffbd5e",
  orange_bright = "#ffdd7e",
  gray = "#7b8496",
}
