#!/usr/bin/env bash
# Shared color palette for all configurations
#
# To change themes: Edit the colors below, then run `make bootstrap`

# ============================================================================
# COLOR PALETTE - Edit these to change your theme
# ============================================================================

# Base colors (Cyberdream.nvim)
THEME_BG="#16181a"              # Main background - Dark gray
THEME_BG_DARK="#0a0a0a"         # Dark background variant - Almost black
THEME_BG_SOFT="#1e2124"         # Soft background - Slightly lighter gray
THEME_BG_MEDIUM="#3c4048"       # Medium background - Highlight background
THEME_FG="#ffffff"              # Main text - White
THEME_FG_DIM="#b0b0b0"          # Dimmed text - Light gray
THEME_FG_FADED="#7b8496"        # Faded text (comments) - Medium gray

# Theme color palette (Cyberdream.nvim)
THEME_RED="#ff6e5e"             # Red
THEME_RED_BRIGHT="#ff8e7e"     # Bright red
THEME_GREEN="#5eff6c"           # Green
THEME_GREEN_BRIGHT="#7eff8c"   # Bright green
THEME_YELLOW="#f1ff5e"          # Yellow
THEME_YELLOW_BRIGHT="#ffff7e"  # Bright yellow
THEME_BLUE="#5ea1ff"            # Blue
THEME_BLUE_BRIGHT="#7eb1ff"    # Bright blue
THEME_PURPLE="#bd5eff"          # Purple
THEME_PURPLE_BRIGHT="#dd7eff"  # Bright purple
THEME_AQUA="#5ef1ff"            # Cyan/Aqua
THEME_AQUA_BRIGHT="#7ef1ff"    # Bright cyan
THEME_ORANGE="#ffbd5e"          # Orange
THEME_ORANGE_BRIGHT="#ffdd7e"  # Bright orange
THEME_GRAY="#7b8496"            # Gray

# Export all theme colors
export THEME_BG THEME_BG_DARK THEME_BG_SOFT THEME_BG_MEDIUM
export THEME_FG THEME_FG_DIM THEME_FG_FADED
export THEME_RED THEME_RED_BRIGHT THEME_GREEN THEME_GREEN_BRIGHT
export THEME_YELLOW THEME_YELLOW_BRIGHT THEME_BLUE THEME_BLUE_BRIGHT
export THEME_PURPLE THEME_PURPLE_BRIGHT THEME_AQUA THEME_AQUA_BRIGHT
export THEME_ORANGE THEME_ORANGE_BRIGHT THEME_GRAY

# ============================================================================
# SEMANTIC TOKENS - Map theme colors to semantic roles (used by all tools)
# ============================================================================
# Change these mappings to switch which colors are used for each role

export TOKEN_BACKGROUND="$THEME_BG"
export TOKEN_BACKGROUND_DARK="$THEME_BG_DARK"
export TOKEN_PRIMARY="$THEME_PURPLE"          # Primary accent (active/focused) - Purple
export TOKEN_SECONDARY="$THEME_AQUA"          # Secondary accent (inactive, cursor) - Cyan
export TOKEN_TEXT="$THEME_FG"
export TOKEN_TEXT_DIM="$THEME_FG_DIM"
export TOKEN_BORDER="$THEME_PURPLE"           # Border color - Purple
export TOKEN_BORDER_INACTIVE="$THEME_GRAY"    # Inactive border

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Convert hex color to RGBA format (0xRRGGBBAA)
# Usage: hex_to_rgba "#RRGGBB" [alpha]
hex_to_rgba() {
  local hex="$1"
  local alpha="${2:-FF}"
  hex="${hex#\#}"
  hex=$(echo "$hex" | tr '[:lower:]' '[:upper:]')
  alpha=$(echo "$alpha" | tr '[:lower:]' '[:upper:]')
  echo "0x${alpha}${hex}"
}

# Generate unified theme files for all tools
generate_all_themes() {
  local config_dir="${1:-}"
  if [ -z "$config_dir" ]; then
    # Default to config directory relative to this script
    local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    config_dir="$script_dir"
  elif [ -f "$config_dir" ]; then
    # If a file path was provided, get its directory
    config_dir="$(dirname "$config_dir")"
    # Go up to config directory if we're in a subdirectory
    if [[ "$config_dir" == *"/kitty" ]] || [[ "$config_dir" == *"/sketchybar" ]] || [[ "$config_dir" == *"/nvim" ]] || [[ "$config_dir" == *"/jankyborders" ]] || [[ "$config_dir" == *"/zsh" ]]; then
      config_dir="$(dirname "$config_dir")"
    fi
  fi
  
  # Generate sketchybar theme
  local sketchybar_theme="$config_dir/sketchybar/theme/colors"
  mkdir -p "$(dirname "$sketchybar_theme")"
  cat > "$sketchybar_theme" <<EOF
# Auto-generated by colors.sh - DO NOT EDIT MANUALLY
# Unified semantic tokens for sketchybar

# Background colors
BACKGROUND=$(hex_to_rgba "$TOKEN_BACKGROUND" "66")
BACKGROUND_SOLID=$(hex_to_rgba "$TOKEN_BACKGROUND")

# Primary color (for active/focused items)
PRIMARY=$(hex_to_rgba "$TOKEN_PRIMARY" "66")
PRIMARY_SOLID=$(hex_to_rgba "$TOKEN_PRIMARY")
PRIMARY_BORDER=$(hex_to_rgba "$TOKEN_PRIMARY")

# Secondary color (for inactive items)
SECONDARY=$(hex_to_rgba "$TOKEN_SECONDARY" "66")
SECONDARY_SOLID=$(hex_to_rgba "$TOKEN_SECONDARY")

# Text colors
TEXT=$(hex_to_rgba "$TOKEN_TEXT")
TEXT_DIM=$(hex_to_rgba "$TOKEN_TEXT_DIM" "CC")

# Shadow
SHADOW=0xA0000000

# Border colors
BORDER_ACTIVE=$(hex_to_rgba "$TOKEN_BORDER")
BORDER_INACTIVE=$(hex_to_rgba "$TOKEN_BORDER_INACTIVE")
EOF

  # Generate kitty theme
  local kitty_theme="$config_dir/kitty/theme/colors.conf"
  mkdir -p "$(dirname "$kitty_theme")"
  cat > "$kitty_theme" <<EOF
# Auto-generated by colors.sh - DO NOT EDIT MANUALLY
# Unified semantic tokens for kitty

# Colors (using unified tokens)
foreground              $TOKEN_TEXT
background              $TOKEN_BACKGROUND
selection_foreground    $TOKEN_BACKGROUND
selection_background    $TOKEN_PRIMARY

# Cursor
cursor                  $TOKEN_SECONDARY
cursor_text_color       $TOKEN_BACKGROUND

# URL underline color
url_color               $TOKEN_SECONDARY

# Window border colors
active_border_color     $TOKEN_BORDER
inactive_border_color   $TOKEN_BORDER_INACTIVE
bell_border_color       $TOKEN_PRIMARY

# Tab bar colors
active_tab_foreground   $TOKEN_BACKGROUND
active_tab_background   $TOKEN_PRIMARY
inactive_tab_foreground $TOKEN_TEXT
inactive_tab_background $TOKEN_BACKGROUND_DARK
tab_bar_background      $TOKEN_BACKGROUND

# Colors for marks
mark1_foreground $TOKEN_BACKGROUND
mark1_background $TOKEN_SECONDARY
mark2_foreground $TOKEN_BACKGROUND
mark2_background $TOKEN_PRIMARY
mark3_foreground $TOKEN_BACKGROUND
mark3_background $TOKEN_PRIMARY

# The 16 terminal colors
color0 $TOKEN_BACKGROUND
color8 $THEME_BG_MEDIUM
color1 $THEME_RED
color9 $THEME_RED_BRIGHT
color2 $THEME_GREEN
color10 $THEME_GREEN_BRIGHT
color3 $THEME_YELLOW
color11 $THEME_YELLOW_BRIGHT
color4 $THEME_BLUE
color12 $THEME_BLUE_BRIGHT
color5 $THEME_PURPLE
color13 $THEME_PURPLE_BRIGHT
color6 $THEME_AQUA
color14 $THEME_AQUA_BRIGHT
color7 $TOKEN_TEXT
color15 $THEME_FG
EOF

  # Generate jankyborders theme
  local jankyborders_theme="$config_dir/jankyborders/theme/colors"
  mkdir -p "$(dirname "$jankyborders_theme")"
  cat > "$jankyborders_theme" <<EOF
# Auto-generated by colors.sh - DO NOT EDIT MANUALLY
# Unified semantic tokens for jankyborders

# Border colors (using unified tokens)
BORDER_ACTIVE=$(hex_to_rgba "$TOKEN_BORDER")
BORDER_INACTIVE=$(hex_to_rgba "$TOKEN_BORDER_INACTIVE")
EOF

  # Generate nvim theme
  local nvim_theme="$config_dir/nvim/lua/theme/colors.lua"
  mkdir -p "$(dirname "$nvim_theme")"
  cat > "$nvim_theme" <<EOF
-- Auto-generated by colors.sh - DO NOT EDIT MANUALLY
-- Unified semantic tokens for neovim

return {
  -- Base colors
  bg = "$TOKEN_BACKGROUND",
  bg_dark = "$TOKEN_BACKGROUND_DARK",
  fg = "$TOKEN_TEXT",
  
  -- Semantic tokens
  primary = "$TOKEN_PRIMARY",
  secondary = "$TOKEN_SECONDARY",
  border = "$TOKEN_BORDER",
  border_inactive = "$TOKEN_BORDER_INACTIVE",
  
  -- Syntax colors (from theme - Gruvbox Modern)
  red = "$THEME_RED",
  red_bright = "$THEME_RED_BRIGHT",
  green = "$THEME_GREEN",
  green_bright = "$THEME_GREEN_BRIGHT",
  yellow = "$THEME_YELLOW",
  yellow_bright = "$THEME_YELLOW_BRIGHT",
  blue = "$THEME_BLUE",
  blue_bright = "$THEME_BLUE_BRIGHT",
  purple = "$THEME_PURPLE",
  purple_bright = "$THEME_PURPLE_BRIGHT",
  aqua = "$THEME_AQUA",
  aqua_bright = "$THEME_AQUA_BRIGHT",
  orange = "$THEME_ORANGE",
  orange_bright = "$THEME_ORANGE_BRIGHT",
  gray = "$THEME_GRAY",
}
EOF

  # Generate p10k theme
  local p10k_theme="$config_dir/zsh/theme/colors"
  mkdir -p "$(dirname "$p10k_theme")"
  cat > "$p10k_theme" <<EOF
# Auto-generated by colors.sh - DO NOT EDIT MANUALLY
# Unified semantic tokens for powerlevel10k
# Source this file in .p10k.zsh to use unified colors

# Base colors (hex format - zsh supports this)
export P10K_BACKGROUND="$TOKEN_BACKGROUND"
export P10K_BACKGROUND_DARK="$TOKEN_BACKGROUND_DARK"
export P10K_FOREGROUND="$TOKEN_TEXT"
export P10K_FOREGROUND_DIM="$TOKEN_TEXT_DIM"

# Semantic tokens
export P10K_PRIMARY="$TOKEN_PRIMARY"
export P10K_SECONDARY="$TOKEN_SECONDARY"
export P10K_BORDER="$TOKEN_BORDER"

# Theme colors for syntax highlighting (Gruvbox Modern)
export P10K_RED="$THEME_RED"
export P10K_RED_BRIGHT="$THEME_RED_BRIGHT"
export P10K_GREEN="$THEME_GREEN"
export P10K_GREEN_BRIGHT="$THEME_GREEN_BRIGHT"
export P10K_YELLOW="$THEME_YELLOW"
export P10K_YELLOW_BRIGHT="$THEME_YELLOW_BRIGHT"
export P10K_BLUE="$THEME_BLUE"
export P10K_BLUE_BRIGHT="$THEME_BLUE_BRIGHT"
export P10K_PURPLE="$THEME_PURPLE"
export P10K_PURPLE_BRIGHT="$THEME_PURPLE_BRIGHT"
export P10K_AQUA="$THEME_AQUA"
export P10K_AQUA_BRIGHT="$THEME_AQUA_BRIGHT"
export P10K_ORANGE="$THEME_ORANGE"
export P10K_ORANGE_BRIGHT="$THEME_ORANGE_BRIGHT"
export P10K_GRAY="$THEME_GRAY"

# Note: p10k uses numeric color codes (0-255) in POWERLEVEL9K_* variables
# You can use these hex values by converting them or using zsh's color system
# Example: typeset -g POWERLEVEL9K_DIR_BACKGROUND=\$P10K_PRIMARY
EOF
}

# Auto-generate all theme files if requested or when executed directly
if [ -n "${GENERATE_THEMES:-}" ]; then
  # If a path was provided as argument, use it as config dir
  if [ -n "${1:-}" ]; then
    generate_all_themes "$1"
  else
    generate_all_themes
  fi
elif [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  # If executed directly, generate all theme files
  generate_all_themes "${1:-}"
fi
