-- Custom colorscheme matching the terminal palette
return {
  {
    "LazyVim/LazyVim",
    opts = {
      -- Use cyberdream as base, we'll override with unified theme colors
      colorscheme = "cyberdream",
    },
  },
  {
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      -- Load unified theme tokens (generated by colors.sh)
      local theme = require("theme.colors")
      
      require("cyberdream").setup({
        variant = "default",
        transparent = true,
        italic_comments = true,
        hide_fillchars = false,
        borderless_pickers = false,
        terminal_colors = true,
        -- Override colors to match unified theme
        colors = {
          bg = theme.bg,
          bg_alt = theme.bg_dark,
          bg_highlight = theme.bg_dark,
          fg = theme.fg,
          grey = theme.gray,
          blue = theme.blue,
          green = theme.green,
          cyan = theme.aqua,
          red = theme.red,
          yellow = theme.yellow,
          magenta = theme.purple_bright,
          pink = theme.purple_bright,
          orange = theme.orange,
          purple = theme.purple,
        },
      })
    end,
  },
}
