-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Custom colorscheme using unified theme tokens
local function setup_custom_colorscheme()
  -- Load unified theme tokens (generated by colors.sh)
  local theme = require("theme.colors")

  -- Color palette using unified tokens
  local colors = {
    -- Base colors (from unified tokens)
    bg = theme.bg,
    bg_dark = theme.bg_dark,
    fg = theme.fg,

    -- Semantic tokens
    primary = theme.primary,
    secondary = theme.secondary,
    border = theme.border,
    border_inactive = theme.border_inactive,

    -- Syntax colors (from theme - Gruvbox Modern)
    red = theme.red,
    red_bright = theme.red_bright,
    green = theme.green,
    green_bright = theme.green_bright,
    yellow = theme.yellow,
    yellow_bright = theme.yellow_bright,
    blue = theme.blue,
    blue_bright = theme.blue_bright,
    purple = theme.purple,
    purple_bright = theme.purple_bright,
    aqua = theme.aqua,
    aqua_bright = theme.aqua_bright,
    orange = theme.orange,
    orange_bright = theme.orange_bright,
    gray = theme.gray,
  }

    local function apply_colors()
    -- Background and foreground (using unified tokens) - force override
    vim.api.nvim_set_hl(0, "Normal", { bg = colors.bg, fg = colors.fg })
    vim.api.nvim_set_hl(0, "NormalFloat", { bg = colors.bg_dark, fg = colors.fg })
    vim.api.nvim_set_hl(0, "NormalNC", { bg = colors.bg, fg = colors.fg })
    
    -- Override common background groups that colorschemes might set
    vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = colors.bg, fg = colors.bg })
    vim.api.nvim_set_hl(0, "NonText", { bg = colors.bg, fg = colors.gray })
    vim.api.nvim_set_hl(0, "SignColumn", { bg = colors.bg })
    vim.api.nvim_set_hl(0, "ColorColumn", { bg = colors.bg_dark })
    vim.api.nvim_set_hl(0, "CursorColumn", { bg = colors.bg_dark })
    vim.api.nvim_set_hl(0, "CursorLine", { bg = colors.bg_dark })

    -- Syntax highlighting
    vim.api.nvim_set_hl(0, "Keyword", { fg = colors.blue_bright, bold = true })
    vim.api.nvim_set_hl(0, "Function", { fg = colors.yellow })
    vim.api.nvim_set_hl(0, "String", { fg = colors.green_bright })
    vim.api.nvim_set_hl(0, "Number", { fg = colors.purple_bright })
    vim.api.nvim_set_hl(0, "Type", { fg = colors.blue_bright, bold = true })
    vim.api.nvim_set_hl(0, "Operator", { fg = colors.aqua_bright })
    vim.api.nvim_set_hl(0, "Tag", { fg = colors.aqua_bright })
    vim.api.nvim_set_hl(0, "Comment", { fg = colors.gray, italic = true })
    vim.api.nvim_set_hl(0, "Constant", { fg = colors.orange_bright })
    vim.api.nvim_set_hl(0, "Identifier", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "Special", { fg = colors.red_bright })
    vim.api.nvim_set_hl(0, "Delimiter", { fg = colors.gray })

    -- Treesitter groups
    vim.api.nvim_set_hl(0, "@keyword", { fg = colors.blue_bright, bold = true })
    vim.api.nvim_set_hl(0, "@function", { fg = colors.yellow })
    vim.api.nvim_set_hl(0, "@function.builtin", { fg = colors.orange_bright })
    vim.api.nvim_set_hl(0, "@string", { fg = colors.green_bright })
    vim.api.nvim_set_hl(0, "@number", { fg = colors.purple_bright })
    vim.api.nvim_set_hl(0, "@type", { fg = colors.blue_bright, bold = true })
    vim.api.nvim_set_hl(0, "@operator", { fg = colors.aqua_bright })
    vim.api.nvim_set_hl(0, "@comment", { fg = colors.gray, italic = true })
    vim.api.nvim_set_hl(0, "@constant", { fg = colors.orange_bright })
    vim.api.nvim_set_hl(0, "@variable", { fg = colors.fg })
    vim.api.nvim_set_hl(0, "@property", { fg = colors.blue_bright })
    vim.api.nvim_set_hl(0, "@punctuation", { fg = colors.gray })
    vim.api.nvim_set_hl(0, "@tag", { fg = colors.aqua_bright })

    -- LSP highlights (using unified tokens)
    vim.api.nvim_set_hl(0, "LspReferenceText", { bg = colors.bg_dark, fg = colors.primary })
    vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = colors.bg_dark, fg = colors.secondary })
    vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = colors.bg_dark, fg = colors.primary })

    -- Diagnostics
    vim.api.nvim_set_hl(0, "DiagnosticError", { fg = colors.red_bright })
    vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = colors.yellow_bright })
    vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = colors.blue_bright })
    vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = colors.aqua_bright })

    -- Cursor and selection (using unified tokens)
    vim.api.nvim_set_hl(0, "Cursor", { bg = colors.secondary, fg = colors.bg })
    vim.api.nvim_set_hl(0, "Visual", { bg = colors.bg_dark, fg = colors.primary })
    vim.api.nvim_set_hl(0, "Search", { bg = colors.bg_dark, fg = colors.yellow_bright })
    vim.api.nvim_set_hl(0, "IncSearch", { bg = colors.yellow_bright, fg = colors.bg })

    -- Line numbers
    vim.api.nvim_set_hl(0, "LineNr", { fg = colors.gray })
    vim.api.nvim_set_hl(0, "CursorLineNr", { fg = colors.secondary, bold = true })

    -- Status line (using unified tokens)
    vim.api.nvim_set_hl(0, "StatusLine", { bg = colors.bg_dark, fg = colors.fg })
    vim.api.nvim_set_hl(0, "StatusLineNC", { bg = colors.bg_dark, fg = colors.gray })

    -- Pmenu (completion menu) (using unified tokens)
    vim.api.nvim_set_hl(0, "Pmenu", { bg = colors.bg_dark, fg = colors.fg })
    vim.api.nvim_set_hl(0, "PmenuSel", { bg = colors.primary, fg = colors.bg })
    vim.api.nvim_set_hl(0, "PmenuSbar", { bg = colors.bg_dark })
    vim.api.nvim_set_hl(0, "PmenuThumb", { bg = colors.gray })

    -- Diff
    vim.api.nvim_set_hl(0, "DiffAdd", { bg = colors.bg_dark, fg = colors.green_bright })
    vim.api.nvim_set_hl(0, "DiffDelete", { bg = colors.bg_dark, fg = colors.red_bright })
    vim.api.nvim_set_hl(0, "DiffChange", { bg = colors.bg_dark, fg = colors.yellow_bright })
    vim.api.nvim_set_hl(0, "DiffText", { bg = colors.bg_dark, fg = colors.blue_bright })

    -- Git signs
    vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = colors.green_bright })
    vim.api.nvim_set_hl(0, "GitSignsChange", { fg = colors.yellow_bright })
    vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = colors.red_bright })

    -- Fold
    vim.api.nvim_set_hl(0, "Folded", { bg = colors.bg_dark, fg = colors.gray })
    vim.api.nvim_set_hl(0, "FoldColumn", { fg = colors.gray })

    -- Border and float (using unified tokens)
    vim.api.nvim_set_hl(0, "FloatBorder", { fg = colors.border })
    vim.api.nvim_set_hl(0, "WinSeparator", { fg = colors.border_inactive })
  end

  -- Apply colors on ColorScheme event (to override any colorscheme changes)
  local color_group = vim.api.nvim_create_augroup("CustomColorscheme", { clear = true })
  vim.api.nvim_create_autocmd("ColorScheme", {
    pattern = "*",
    callback = function()
      -- Defer to ensure we override after colorscheme fully loads
      vim.defer_fn(apply_colors, 10)
    end,
    group = color_group,
  })

  -- Apply colors immediately
  apply_colors()
  
  -- Also apply after a short delay to ensure override
  vim.defer_fn(apply_colors, 100)
end

-- Setup colorscheme as early as possible
local colorscheme_group = vim.api.nvim_create_augroup("CustomColorschemeSetup", { clear = true })

-- Apply on VimEnter (after all plugins load)
vim.api.nvim_create_autocmd("VimEnter", {
  callback = setup_custom_colorscheme,
  group = colorscheme_group,
})

-- Also apply on VeryLazy (LazyVim's event)
vim.api.nvim_create_autocmd("User", {
  pattern = "VeryLazy",
  callback = setup_custom_colorscheme,
  group = colorscheme_group,
})
